// <auto-generated />
using System;
using Athlitix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Athlitix.Migrations
{
    [DbContext(typeof(AthlitixContext))]
    [Migration("20260207155106_Add participants")]
    partial class Addparticipants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athlitix.Entities.AdminEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df283585-df16-42d2-aa51-b10eb2861b7e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "skate.mccartney@hotmail.com",
                            FirstName = "Skate",
                            IsActive = true,
                            LastName = "McCartney",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            PasswordHash = "YQORdMCqDS1x+FTFEClDB19c0XD5YtlrKSHGVfUR0/I=",
                            PhoneNumber = "01132678544",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FinishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Competition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Season finaly for all the greatest fighters",
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            Name = "Legends Final",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8f3a2c1b-4d7e-4a9f-8b2d-1c0e9f7a6b5d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thrilling summer event bringing together top amateurs for fast-paced bouts.",
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            Name = "Summer Showdown",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d4e7a1b2-3c8f-4d5a-9e7b-2f1c0a8d9e6b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kicking off August with fierce matchups across all weight categories.",
                            FinishDate = new DateTimeOffset(new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            Name = "August Clash",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            StartDate = new DateTimeOffset(new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FinishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("101a7f3c-9c2b-4f1a-9e3d-6c5a4b3d2e01"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur lightweight division (Under 60kg).",
                            EventTypeId = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 60kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("202b8e4d-1a3c-4b2d-8f9e-7d6c5b4a3e02"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur light-middleweight division (Under 71kg).",
                            EventTypeId = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 71kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("303c9d5e-2b4d-4c3e-9a8f-8e7d6c5b4a03"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur bantamweight division (Under 54kg).",
                            EventTypeId = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 54kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("404d0c6f-3c5e-4d4f-8b7a-9f8e7d6c5b04"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur light-heavyweight division (Under 80kg).",
                            EventTypeId = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 80kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 20, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("505e1b7a-4d6f-4e5a-9c8b-0a9f8e7d6c05"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur light-welterweight division (Under 63.5kg).",
                            EventTypeId = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 63.5kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("606f2a8b-5e7a-4f6b-8d9c-1b0a9f8e7d06"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur heavyweight division (Under 92kg).",
                            EventTypeId = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 92kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("707a3b9c-6f8b-4a7c-9e0d-2c1b0a9f8e07"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur featherweight division (Under 57kg).",
                            EventTypeId = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Under 57kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("808b4cad-7a9c-4b8d-8f1e-3d2c1b0a9f08"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men's amateur super-heavyweight division (Over 92kg).",
                            EventTypeId = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 7, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Men's Over 92kg Open",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 7, 21, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.EventTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EventType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cac94e39-969d-41ef-9a25-f33675e1fe92"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Under 13's non competitive skills fight",
                            IsActive = true,
                            Name = "Skills Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Junior competitive skills fight",
                            IsActive = true,
                            Name = "Junior Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Senior competitive skills fight",
                            IsActive = true,
                            Name = "Senior Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kicking arse since 2018",
                            IsActive = true,
                            Name = "Elite Muay Thai"
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Participant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000001-1111-4111-8111-111111111001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2006, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "jack.smith1@example.com",
                            FirstName = "Jack",
                            HeightCm = 172m,
                            IsActive = true,
                            LastName = "Smith",
                            NickName = "Tank",
                            PasswordHash = "",
                            PhoneNumber = "07470000001",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0001"),
                            WeightKg = 67m
                        },
                        new
                        {
                            Id = new Guid("b1000002-1111-4111-8111-111111111002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2005, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "tom.jones2@example.com",
                            FirstName = "Tom",
                            HeightCm = 178m,
                            IsActive = true,
                            LastName = "Jones",
                            NickName = "Flash",
                            PasswordHash = "",
                            PhoneNumber = "07470000002",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0001"),
                            WeightKg = 71m
                        },
                        new
                        {
                            Id = new Guid("b1000003-1111-4111-8111-111111111003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2004, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "harry.brown3@example.com",
                            FirstName = "Harry",
                            HeightCm = 180m,
                            IsActive = true,
                            LastName = "Brown",
                            NickName = "Hammer",
                            PasswordHash = "",
                            PhoneNumber = "07470000003",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0001"),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("b1000004-1111-4111-8111-111111111004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2007, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "liam.taylor4@example.com",
                            FirstName = "Liam",
                            HeightCm = 175m,
                            IsActive = true,
                            LastName = "Taylor",
                            NickName = "Ace",
                            PasswordHash = "",
                            PhoneNumber = "07470000004",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0002"),
                            WeightKg = 63.5m
                        },
                        new
                        {
                            Id = new Guid("b1000005-1111-4111-8111-111111111005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2003, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "josh.wilson5@example.com",
                            FirstName = "Josh",
                            HeightCm = 182m,
                            IsActive = true,
                            LastName = "Wilson",
                            NickName = "Crusher",
                            PasswordHash = "",
                            PhoneNumber = "07470000005",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0003"),
                            WeightKg = 80m
                        },
                        new
                        {
                            Id = new Guid("b1000006-1111-4111-8111-111111111006"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2008, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ben.walker6@example.com",
                            FirstName = "Ben",
                            HeightCm = 170m,
                            IsActive = true,
                            LastName = "Walker",
                            NickName = "Spike",
                            PasswordHash = "",
                            PhoneNumber = "07470000006",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0004"),
                            WeightKg = 60m
                        },
                        new
                        {
                            Id = new Guid("b1000007-1111-4111-8111-111111111007"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2006, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "sam.white7@example.com",
                            FirstName = "Sam",
                            HeightCm = 176m,
                            IsActive = true,
                            LastName = "White",
                            NickName = "Storm",
                            PasswordHash = "",
                            PhoneNumber = "07470000007",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0005"),
                            WeightKg = 67m
                        },
                        new
                        {
                            Id = new Guid("b1000008-1111-4111-8111-111111111008"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2002, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "ryan.hall8@example.com",
                            FirstName = "Ryan",
                            HeightCm = 185m,
                            IsActive = true,
                            LastName = "Hall",
                            NickName = "Blade",
                            PasswordHash = "",
                            PhoneNumber = "07470000008",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0006"),
                            WeightKg = 85m
                        },
                        new
                        {
                            Id = new Guid("b1000009-1111-4111-8111-111111111009"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2004, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "luke.turner9@example.com",
                            FirstName = "Luke",
                            HeightCm = 179m,
                            IsActive = true,
                            LastName = "Turner",
                            NickName = "Beast",
                            PasswordHash = "",
                            PhoneNumber = "07470000009",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0007"),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("b1000010-1111-4111-8111-111111111010"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "callum.harris10@example.com",
                            FirstName = "Callum",
                            HeightCm = 183m,
                            IsActive = true,
                            LastName = "Harris",
                            NickName = "Bulldog",
                            PasswordHash = "",
                            PhoneNumber = "07470000010",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0008"),
                            WeightKg = 90m
                        },
                        new
                        {
                            Id = new Guid("b1000011-1111-4111-8111-111111111011"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2007, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jake.roberts11@example.com",
                            FirstName = "Jake",
                            HeightCm = 174m,
                            IsActive = true,
                            LastName = "Roberts",
                            NickName = "Rocket",
                            PasswordHash = "",
                            PhoneNumber = "07470000011",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0009"),
                            WeightKg = 63.5m
                        },
                        new
                        {
                            Id = new Guid("b1000012-1111-4111-8111-111111111012"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2004, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "connor.clarke12@example.com",
                            FirstName = "Connor",
                            HeightCm = 181m,
                            IsActive = true,
                            LastName = "Clarke",
                            NickName = "Iron",
                            PasswordHash = "",
                            PhoneNumber = "07470000012",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0010"),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("b1000013-1111-4111-8111-111111111013"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2005, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dan.wood13@example.com",
                            FirstName = "Dan",
                            HeightCm = 177m,
                            IsActive = true,
                            LastName = "Wood",
                            NickName = "Knuckles",
                            PasswordHash = "",
                            PhoneNumber = "07470000013",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0011"),
                            WeightKg = 71m
                        },
                        new
                        {
                            Id = new Guid("b1000014-1111-4111-8111-111111111014"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2002, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "alex.thompson14@example.com",
                            FirstName = "Alex",
                            HeightCm = 184m,
                            IsActive = true,
                            LastName = "Thompson",
                            NickName = "Shadow",
                            PasswordHash = "",
                            PhoneNumber = "07470000014",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0012"),
                            WeightKg = 85m
                        },
                        new
                        {
                            Id = new Guid("b1000015-1111-4111-8111-111111111015"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2003, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "max.jackson15@example.com",
                            FirstName = "Max",
                            HeightCm = 179m,
                            IsActive = true,
                            LastName = "Jackson",
                            NickName = "Hammer",
                            PasswordHash = "",
                            PhoneNumber = "07470000015",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0013"),
                            WeightKg = 80m
                        },
                        new
                        {
                            Id = new Guid("b1000016-1111-4111-8111-111111111016"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2008, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "ollie.turner16@example.com",
                            FirstName = "Ollie",
                            HeightCm = 171m,
                            IsActive = true,
                            LastName = "Turner",
                            NickName = "Flash",
                            PasswordHash = "",
                            PhoneNumber = "07470000016",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0014"),
                            WeightKg = 60m
                        },
                        new
                        {
                            Id = new Guid("b1000017-1111-4111-8111-111111111017"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2006, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "charlie.wright17@example.com",
                            FirstName = "Charlie",
                            HeightCm = 176m,
                            IsActive = true,
                            LastName = "Wright",
                            NickName = "Ace",
                            PasswordHash = "",
                            PhoneNumber = "07470000017",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0015"),
                            WeightKg = 67m
                        },
                        new
                        {
                            Id = new Guid("b1000018-1111-4111-8111-111111111018"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2004, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "theo.patel18@example.com",
                            FirstName = "Theo",
                            HeightCm = 182m,
                            IsActive = true,
                            LastName = "Patel",
                            NickName = "Storm",
                            PasswordHash = "",
                            PhoneNumber = "07470000018",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0016"),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("b1000019-1111-4111-8111-111111111019"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2001, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "ethan.davies19@example.com",
                            FirstName = "Ethan",
                            HeightCm = 186m,
                            IsActive = true,
                            LastName = "Davies",
                            NickName = "Bulldog",
                            PasswordHash = "",
                            PhoneNumber = "07470000019",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0017"),
                            WeightKg = 90m
                        },
                        new
                        {
                            Id = new Guid("b1000020-1111-4111-8111-111111111020"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(1999, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ryan.green20@example.com",
                            FirstName = "Ryan",
                            HeightCm = 188m,
                            IsActive = true,
                            LastName = "Green",
                            NickName = "Beast",
                            PasswordHash = "",
                            PhoneNumber = "07470000020",
                            TeamId = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0018"),
                            WeightKg = 100m
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Team", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fearless fighters roaring out of central Leeds",
                            IsActive = true,
                            Name = "LS1 Leeds Lions",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grit-fueled brawlers built for pressure fights",
                            IsActive = true,
                            Name = "M1 Manchester Maulers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Forged tough with relentless knockout power",
                            IsActive = true,
                            Name = "S6 Sheffield Steel",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast-handed fighters with championship ambition",
                            IsActive = true,
                            Name = "L2 Liverpool Legends",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Late-round warriors with ruthless finishes",
                            IsActive = true,
                            Name = "NE1 Newcastle Nightfall",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0006"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Midlands muscle with heavy-hitting intent",
                            IsActive = true,
                            Name = "B1 Birmingham Brutes",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0007"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Precision punchers with outlaw mentality",
                            IsActive = true,
                            Name = "NG1 Nottingham Knockout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0008"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explosive speed and high-volume attacks",
                            IsActive = true,
                            Name = "LE1 Leicester Lightning",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0009"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breakdown specialists who wear opponents out",
                            IsActive = true,
                            Name = "CV1 Coventry Crushers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0010"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ring control experts with suffocating pressure",
                            IsActive = true,
                            Name = "DE1 Derby Dominators",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0011"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elite-level fighters chasing national dominance",
                            IsActive = true,
                            Name = "EC1 London Empire",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0012"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smooth operators with sudden knockout power",
                            IsActive = true,
                            Name = "BN1 Brighton Breakers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0013"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sharp-shooting south coast contenders",
                            IsActive = true,
                            Name = "SO14 Southampton Strikers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0014"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hard-nosed fighters with navy-town toughness",
                            IsActive = true,
                            Name = "PO1 Portsmouth Punishers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0015"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern warriors with old-school grit",
                            IsActive = true,
                            Name = "GU1 Guildford Gladiators",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0016"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart, technical fighters with killer instinct",
                            IsActive = true,
                            Name = "CB1 Cambridge Combat",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0017"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Street-bred toughness with pro-level skill",
                            IsActive = true,
                            Name = "BS1 Bristol Brawlers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0018"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Southern grit with relentless pressure style",
                            IsActive = true,
                            Name = "EX1 Exeter Enforcers",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0019"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tidal-force punchers from the southwest",
                            IsActive = true,
                            Name = "PL1 Plymouth Power",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("a1c3b6c2-4d5f-4c2a-9a01-1f7b1c9a0020"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Calculated destruction with elite ring IQ",
                            IsActive = true,
                            Name = "OX1 Oxford Overlords",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.AdminEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("Admins")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("Competitions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.EventEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.CompetitionEntity", "Competition")
                        .WithMany("Events")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Athlitix.Entities.EventTypeEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("EventTypes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.ParticipantEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.TeamEntity", "Team")
                        .WithMany("Participants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Athlitix.Entities.TeamEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Athlitix.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Competitions");

                    b.Navigation("EventTypes");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Athlitix.Entities.TeamEntity", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
