// <auto-generated />
using System;
using Athlitix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Athlitix.Migrations
{
    [DbContext(typeof(AthlitixContext))]
    [Migration("20260125215737_Add participant")]
    partial class Addparticipant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athlitix.Entities.AdminEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df283585-df16-42d2-aa51-b10eb2861b7e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "skate.mccartney@hotmail.com",
                            FirstName = "Skate",
                            IsActive = true,
                            LastName = "McCartney",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            PasswordHash = "YQORdMCqDS1x+FTFEClDB19c0XD5YtlrKSHGVfUR0/I=",
                            PhoneNumber = "01132678544",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FinishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Competition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Season finaly for all the greatest fighters",
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            Name = "Legends Final",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FinishDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2dbfda-3842-4bd9-a063-00d5fde0c9a0"),
                            CompetitionId = new Guid("561e6139-413c-4de6-bbdc-6c58bb3b61aa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            EventTypeId = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            FinishDate = new DateTimeOffset(new DateTime(2026, 7, 1, 19, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            Name = "70kg - Skate McCartney vs Abdul Mohadeen",
                            StartDate = new DateTimeOffset(new DateTime(2026, 7, 1, 19, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.EventTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EventType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cac94e39-969d-41ef-9a25-f33675e1fe92"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Under 13's non competitive skills fight",
                            IsActive = true,
                            Name = "Skills Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("dbc5f1de-fcba-4d0a-8a71-eeb1f209eeff"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Junior competitive skills fight",
                            IsActive = true,
                            Name = "Junior Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("d9fdad56-2c37-4be7-89ab-1af3cf1142c7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Senior competitive skills fight",
                            IsActive = true,
                            Name = "Senior Bout",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kicking arse since 2018",
                            IsActive = true,
                            Name = "Elite Muay Thai"
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id");

                    b.ToTable("Participant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e6db761-6057-427b-afe5-d575f97c00e7"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2008, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "chunkz@hotmail.com",
                            FirstName = "Joe",
                            HeightCm = 170m,
                            IsActive = true,
                            LastName = "McCartney",
                            NickName = "Chunkz",
                            PasswordHash = "",
                            PhoneNumber = "07470797908",
                            TeamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            WeightKg = 65m
                        },
                        new
                        {
                            Id = new Guid("09c7c50f-b897-4586-be37-719fd9d11893"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(1999, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "matt@hotmail.com",
                            FirstName = "Matthew",
                            HeightCm = 173m,
                            IsActive = true,
                            LastName = "McCartney",
                            NickName = "Matt",
                            PasswordHash = "",
                            PhoneNumber = "07470797908",
                            TeamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("93d6abd2-4651-4a21-9fc5-e9695fc66821"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(2001, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "moron@hotmail.com",
                            FirstName = "Elon",
                            HeightCm = 169m,
                            IsActive = true,
                            LastName = "Musk",
                            NickName = "Moron",
                            PasswordHash = "",
                            PhoneNumber = "07470797908",
                            TeamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            WeightKg = 66m
                        },
                        new
                        {
                            Id = new Guid("f4e127d6-6af7-43c9-a471-cf944364f892"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTimeOffset(new DateTime(1997, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Email = "chuck@hotmail.com",
                            FirstName = "Chuck",
                            HeightCm = 165m,
                            IsActive = true,
                            LastName = "Norris",
                            NickName = "Chuck",
                            PasswordHash = "",
                            PhoneNumber = "07470797908",
                            TeamId = new Guid("00000000-0000-0000-0000-000000000000"),
                            WeightKg = 61m
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Team", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("caccb9c5-7556-47a2-848c-176cee5dc643"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guisleys premiere boxing club",
                            IsActive = true,
                            Name = "LS20 Boxing",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        },
                        new
                        {
                            Id = new Guid("0e37b6b5-2a35-4e33-907e-f1c6c0ad7423"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guisleys premiere boxing club",
                            IsActive = true,
                            Name = "Henrys Boxing",
                            OrganizationId = new Guid("5835ca66-1356-42a5-a36a-cf1a019189f1")
                        });
                });

            modelBuilder.Entity("Athlitix.Entities.AdminEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("Admins")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("Competitions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.EventEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.CompetitionEntity", "Competition")
                        .WithMany("Events")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Athlitix.Entities.EventTypeEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany("EventTypes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.TeamEntity", b =>
                {
                    b.HasOne("Athlitix.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Athlitix.Entities.CompetitionEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Athlitix.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Competitions");

                    b.Navigation("EventTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
